name: e2e Tests
 
on: [pull_request]
 
jobs:
  run-e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: find_a_friend_api_pg
 
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-node@v3
        with:
         node-version: 22
         cache: 'npm'
 
      - run: npm ci
 
      - run: npm run test:e2e
        env:
          JWT_TOKEN: findafriend
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/find_a_friend_api_pg?schema=public"